export const LOGIN_SUCCESS = "USERS_LOGIN_SUCCESS";
export const LOGIN_FAILURE = "USERS_LOGIN_FAILURE";
export const LOGOUT = "USERS_LOGOUT";
export const SET_USER_LANGUAGE = "SET_USER_LANGUAGE";
export const SET_USER = "SET_USER";
